import React, { useState, useEffect } from 'react'
import { connect } from 'react-redux'
import Notification from 'react-native-push-notification'
import { modificaMensagem, enviarMensagem, conversaPetFetch } from '../../store/chat/actions'
import { View, TextInput, FlatList, Text, Image } from 'react-native'
import _ from 'lodash'

import { Button } from 'react-native-elements'

import styles from './styles'

function ChatItem(props) {

    const [dataSource, setDataSource] = useState()
    const situacao = props.navigation.getParam('tipo')
    const [ tipo, setTipo ] = useState('')

    const { pets } = props.usuario
    useEffect(() => {
        const amigo = props.navigation.getParam('model')
        const pet = pets
        let model = {
            amigo,
            pet
        }
        props.conversaPetFetch(model)
        criarFonteDados(props.conversa)
    }, [])

    useEffect(() => {
        criarFonteDados(props.conversa)

    }, [props.conversa])




    function _enviarMensagem() {
        const amigo_pet = props.navigation.getParam('model')
        const pet = pets
        const { mensagem } = props.mensagem
        const model = {
            amigo_pet,
            mensagem,
            pet
        }

        props.enviarMensagem(model)

    }


    function notificarMensagem(nome, menssagem) {
        const notification = `Notificação PetMeet `
        const conteudo = `${nome}: ${menssagem}`
        Notification.localNotification({
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: notification, // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: conteudo, // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification
            priority: "high", // (optional) set notification priority, default: high
            visibility: "private", // (optional) set notification visibility, default: private
            importance: "high", // (optional) set notification importance, default: high


            /* iOS and Android properties */
            title: notification, // (optional)
            message: conteudo, // (required)
            playSound: false, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            repeatType: 'day'
        })
    }

    function criarFonteDados(conversa) {
        setDataSource(conversa)

    }


    function renderRow({ item }) {
        const mensagem = _.get(item, 'mensagem')
        const tipo = _.get(item, 'tipo')
        const imagem = _.get(item, 'imagem')
        if (tipo === 'e') {
            return (
                <View style={styles.mensagemLeft}>
                    <View style={{ flexDirection: 'row' }}>
                        <Text style={styles.textMensagem}>{mensagem}</Text>
                        <Image source={{ uri: imagem }} style={{ height: 30, width: 30, borderRadius: 60 }} />

                    </View>

                </View>
            )
        } else {
            return (
                <View style={styles.mensagemRigth}>
                    <View style={{ flexDirection: 'row' }}>
                        <Text style={styles.textMensagemRigth}>{mensagem}</Text>
                        <Image source={{ uri: imagem }} style={{ height: 30, width: 30, borderRadius: 60 }} />
                    </View>

                </View>
            )
        }

    }

    let backGround = situacao ? { backgroundColor: '#BBDEFB' } : { backgroundColor: '#E57373' }
    return (
        <View style={[styles.container, backGround]}>
            <View style={styles.listContainer}>
                <FlatList data={dataSource}
                    renderItem={renderRow}
                    keyExtractor={item => String(item.uid)}
                />
            </View>
            <View style={styles.sendContainer}>
                <TextInput
                    style={styles.input}
                    placeholder="Digite sua mensagem..."
                    value={props.mensagem}
                    onChangeText={texto => props.modificaMensagem(texto)} />

                <Button title="Enviar"
                    buttonStyle={{ borderRadius: 10, height: 50 }}
                    onPress={_enviarMensagem} />
            </View>
        </View>
    )
}

const mapStateToProps = ({ mensagem, lista, usuario }) => {
    const conversa = _.map(lista, (val, uid) => {

        return { ...val, uid }
    })

    return ({
        conversa,
        mensagem: mensagem,
        usuario
    })
}



export default connect(mapStateToProps, { modificaMensagem, enviarMensagem, conversaPetFetch })(ChatItem)